### ISSUE TITLE
Provide examples

### ISSUE THREAD

**Issue by dxvid-pts** [peterscodee/miniplayer#1]
Provide examples to help developers use the package.

**Comment by dxvid-pts** [comment]
Examples provided in miniplayer 0.4.0

**Comment by alberduris** [comment]
Hi @peterscodee,

Could you post the code of the demo that is shown on the main page? That would be useful! Thanks

**Comment by dxvid-pts** [comment]
[lib.zip](https://github.com/peterscodee/miniplayer/files/5651830/lib.zip)

**Comment by alberduris** [comment]
Great! Thank you very much
