### ISSUE TITLE
Bug: doesn't adhere to darktheme

### ISSUE THREAD

**Issue by MagnusJohansson** [peterscodee/miniplayer#13]
Hi,

just tested this package with a device with system dark theme.
However, it doesn't change the background color of the player, it seems to be hard coded to white.

Fix: in miniplayer.dart
https://github.com/peterscodee/miniplayer/blob/4fa9d07e59d74c0a566ccdb6469fa1338b417c38/lib/miniplayer.dart#L206

Please consider changing:
`color: Colors.white,`

to

`color: Theme.of(context).canvasColor`

Thanks.

**Comment by dxvid-pts** [comment]
Thank you for submitting!
