### ISSUE TITLE
Overflow warnings in example

### ISSUE THREAD

**Issue by shahmirzali49** [peterscodee/miniplayer#14]
A RenderFlex overflowed by 26 pixels on the bottom.

<img width="1405" alt="Screen Shot 2021-04-28 at 17 05 42" src="https://user-images.githubusercontent.com/49102327/116408656-219b4b00-a844-11eb-8d6c-73c63b45a561.png">

**Comment by asterisk37n** [comment]
same here. found a solution?

**Comment by sahmirzali** [comment]
I fork this repo, and solved myself, it you download this fork repo, enter my repository, you will find

**Comment by nwatab** [comment]
same here. found a solution?

**Comment by shahmirzali49** [comment]
@asterisk37n I'm  not using like in example version, I just open issue for this error

**Comment by asterisk37n** [comment]
Thank you. It only happens during translation.

**Comment by nwatab** [comment]
Thank you. I happens only during translation.

> ❯ flutter doctor 
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-JP)
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 4.1)
> [✓] VS Code (version 1.58.2)
> [✓] Connected device (2 available)
> 
>• No issues found!

```dart
bottomNavigationBar: ValueListenableBuilder(
    valueListenable: playerExpandProgress,
    builder: (BuildContext context, double height, Widget? child) {
      final value = _percentageFromValueInRange(
        min: _playerMinHeight,
        max: MediaQuery.of(context).size.height,
        value: height,
      );
      final double opacity =  _clipValueInRange(value: 1.0 - value, min: 0.0, max: 1.0);
      return SizedBox(
        height: kBottomNavigationBarHeight * (1 - value),
        child: Transform.translate(
          offset: Offset(0.0, kBottomNavigationBarHeight * value * 0.5),
          child: Opacity(opacity: opacity, child: child),
        ),
      );
    },
    child: BottomNavigationBar(...),
)

double _percentageFromValueInRange(
    {required final double min,
    required final double max,
    required final double value}) {
  return (value - min) / (max - min);
}

double _clipValueInRange(
    {required final double value,
    required final double min,
    required final double max}) {
  if (value < min) {
    return min;
  }
  if (value > max) {
    return max;
  }
  return value;
}
```

> ═╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
> The following assertion was thrown during layout:
> A RenderFlex overflowed by 29 pixels on the bottom.
> 
> The relevant error-causing widget was:
> BottomNavigationBar file:***
> 
> To inspect this widget in Flutter DevTools, visit:
> http://127.0.0.1:54097/#/inspector?uri=***
> 
> The overflowing RenderFlex has an orientation of Axis.vertical.
> The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
> black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
> Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
> RenderFlex to fit within the available space instead of being sized to their natural size.
> This is considered an error condition because it indicates that there is content that cannot be
> seen. If the content is legitimately bigger than the available space, consider clipping it with a
> ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
> like a ListView.
> The specific RenderFlex in question is: RenderFlex#8f1aa relayoutBoundary=up10 OVERFLOWING:
> creator: Column ← Padding ← Listener ← RawGestureDetector ← GestureDetector ← Semantics ←
> _RawMouseRegion ← MouseRegion ← Semantics ← _FocusMarker ← Focus ← _ActionsMarker ← ⋯
> parentData: offset=Offset(0.0, 7.0) (can use size)
> constraints: BoxConstraints(0.0<=w<=137.1, 0.0<=h<=10.7)
> size: Size(137.1, 10.7)
> direction: vertical
> mainAxisAlignment: spaceBetween
> mainAxisSize: min
> crossAxisAlignment: center
> verticalDirection: down
> ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
> ════════════════════════════════════════════════════════════════════════════════════════════════════
> 
> Another exception was thrown: A RenderFlex overflowed by 29 pixels on the bottom.
> 
> Another exception was thrown: A RenderFlex overflowed by 29 pixels on the bottom.

![image](https://user-images.githubusercontent.com/16299750/127525988-97645759-ffb7-4824-a1a8-62ad8a3137c9.png)
![image](https://user-images.githubusercontent.com/16299750/127526136-d1d630c3-9b3a-4b91-aa68-9ebfc438d5a7.png)

**Comment by nwatab** [comment]
I reproduced the overflow with the `lib.zip` from #1 
![a_mini_player_example_with_an_overflow_bug (1)](https://user-images.githubusercontent.com/16299750/127540709-201186e5-9c7f-4915-b279-22c448fa1f87.gif)

**Comment by mrripp3r** [comment]
Anyone got a work around yet?

**Comment by dxvid-pts** [comment]
I don't see this as a critical issue since it is not visible in production, but this is fixed in 2ad75d4f6f3f92b33ded418dc5c85f671ac94ed6

**Comment by hpulst** [comment]
Overflow warnings do still occur (tested on iOS Simulator).

**Comment by chaevid** [comment]
I solved this problem by adding the 

> [**MediaQuery.of(context).padding.bottom**](https://api.flutter.dev/flutter/widgets/MediaQueryData-class.html)

with the height value of 0 on iPhone 8.

**~/example/lib/main.dart**

[Before]
```
...
          return SizedBox(
            height: kBottomNavigationBarHeight - kBottomNavigationBarHeight * value,
...
```
[After]
```
...
          return SizedBox(
            height: (kBottomNavigationBarHeight + MediaQuery.of(context).padding.bottom) -
                (kBottomNavigationBarHeight + MediaQuery.of(context).padding.bottom) * value,
...
```
