### ISSUE TITLE
type 'int' is not a subtype of type 'double'

### ISSUE THREAD

**Issue by shahmirzali49** [peterscodee/miniplayer#15]
when dismissing giving this error - > type 'int' is not a subtype of type 'double'

**Comment by toklive** [comment]
I am getting the same when the device goes to portrait mode..

I am using ValueNotifier for miniplayer..

 final ValueNotifier<double> customValueNotifier =
        ValueNotifier(MediaQuery.of(context).size.height);

Miniplayer(
                          controller: _videoController.miniPlayerController,
                          **valueNotifier: customValueNotifier,**
                          minHeight: _playerMinHeight,

Here is the call stack..

/flutter (10556): _ValueListenableBuilderState<double>#7a816):
I/flutter (10556): type 'int' is not a subtype of type 'double'
I/flutter (10556):
I/flutter (10556): The relevant error-causing widget was:
I/flutter (10556):   Miniplayer
I/flutter (10556):
lib/…/views/home_view.dart:55
I/flutter (10556):
I/flutter (10556): When the exception was thrown, this was the stack:
I/flutter (10556): #0      borderDouble
**package:miniplayer/src/utils.dart:24**
I/flutter (10556): #1      _MiniplayerState.build.<anonymous closure>
**package:miniplayer/miniplayer.dart:169**
I/flutter (10556): #2      _ValueListenableBuilderState.build
package:flutter/…/widgets/value_listenable_builder.dart:187
I/flutter (10556): #3      StatefulElement.build
package:flutter/…/widgets/framework.dart:4691

**Comment by shahmirzali49** [comment]
Did you solve or? I solved, add github and add to protect from github url, like package

**Comment by toklive** [comment]
Is this package/repo is been maintained? Not seeing any response recently on any issues....

**Comment by toklive** [comment]
> Did you solve or? I solved, add github and add to protect from github url, like package

Nope I didn't resolve it yet. How did you resolve ? Any plan to merge it with this package via PR ?

**Comment by shahmirzali49** [comment]
@toklive - https://github.com/Shahmirzali-Huseynov/miniplayer_for_araf

no, I'm not owner this package, there is the link above solved version.

**Comment by shahmirzali49** [comment]
add pubspecyaml 

miniplayer:
    git:
      url: git://github.com/Shahmirzali-Huseynov/miniplayer_for_araf.git

**Comment by shahmirzali49** [comment]
<img width="560" alt="Screen Shot 2021-06-24 at 00 03 36" src="https://user-images.githubusercontent.com/49102327/123160787-a17a1600-d47f-11eb-832b-abf172a6267c.png">

like this

**Comment by shahmirzali49** [comment]
also you can add your repository and use it from there

**Comment by toklive** [comment]
Great thank you. I will do also I may send a PR with the change..

**Comment by toklive** [comment]
I just did the same change and pushed for PR here.. I will my local repo for the time being like you did.

**Comment by shahmirzali49** [comment]
I don't know unfortunately

**Comment by dxvid-pts** [comment]
I'll take a look this week!

**Comment by steevedevops** [comment]
I solved this problem..
