### ISSUE TITLE
Animate image and controls

### ISSUE THREAD

**Issue by frazras** [peterscodee/miniplayer#2]
Hi, I was hoping that in the example you would have shown how you animated the audio image and the player controls to scale with the player. Do you have an example that shows the animation, otherwise, can you give a simple explanation on how you accomplished it?

**Comment by dxvid-pts** [comment]
Sure. Here is an example where I used the package: [player.dart](https://github.com/peterscodee/podcastproject/blob/master/lib/widgets/player.dart).
What you need when you want to scale an image with the player is the minWidth and the maxWidth. Then you can calculate the current width with the percentage variable passed through the builder function.
```
//Calculates n within a range of values
double valueFromPercentageInRange(
    {@required final double min, max, percentage}) {
  return percentage * (max - min) + min;
}
```

I can give you an example tomorrow if you're still having problems.

**Comment by dxvid-pts** [comment]
@frazras do you need further help or can I close the issue?
