### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by dmckminard** [peterscodee/miniplayer#23]
Hello,

Thank you for this very efficient plugin! I would like to be able to customize it more and make the background color transparent or blurred, is it possible?
Despite several days of testing, I never managed to do it.

**Comment by szeidner** [comment]
@dmckminard Did you figure out how to make the background transparent? I'm running into the same issue.

**Comment by dmckminard** [comment]
@szeidner The only way I found is to duplicate the package in my project and to change in the file "miniplayer.dart" the line 212 : color: Colors.black45,
To Colors.transparent

It's not ideal, but it works!
