### ISSUE TITLE
Option to set initial snap position of the Miniplayer

### ISSUE THREAD

**Issue by vishal-akg** [peterscodee/miniplayer#4]
Instead of having always start from min snap position, there should be an option to customise initial snap position. That can be anything in between max and min.

**Comment by vishal-akg** [comment]
I have tried a workaround this-
 `_playerExpandProgress = ValueNotifier({max height of device});`
But then the issue arises because you don't consider its initial value in initState method.  you have simply assumed it to be always _dragHeight minHeight;

I made these following changes;-

`if (widget.valueNotifier == null) {
      heightNotifier = ValueNotifier(widget.minHeight);
      _dragHeight = min.maxHeight;
    } else {
      heightNotifier = widget.valueNotifier;
      _dragHeight = widget.valueNotifer.value;
    }`

Just review it please.

**Comment by dxvid-pts** [comment]
You can achieve that through providing a custom `ValueNotifier`:

```dart
final ValueNotifier<double> customValueNotifier =
    ValueNotifier(INITIAL_HEIGHT);

Miniplayer(
    valueNotifier: customValueNotifier,
),
```

I'm not completely convinced that it is required to add a new parameter as I don't want the list to get messy over time. Do you still think we should add a new parameter?

**Comment by vishal-akg** [comment]
yes I am using valueNotifier to initially show miniplayer in expanded state, but then on drag down it doesn't work as expected, First drag down gesture it won't minimise.

**Comment by dxvid-pts** [comment]
Ok, I'll take a look tomorrow.

**Comment by dxvid-pts** [comment]
> yes I am using valueNotifier to initially show miniplayer in expanded state, but then on drag down it doesn't work as expected, First drag down gesture it won't minimise.

[Fixed](https://github.com/peterscodee/miniplayer/commit/4d7cf691260f5049f7574b3ec25284cda9f5b3d2).
