### ISSUE TITLE
No programmatic way of switching between snap position.

### ISSUE THREAD

**Issue by vishal-akg** [peterscodee/miniplayer#5]
Suppose I want to snap to min when a user presses back button, and back to snap snap max when clicked on different button.

**Comment by dxvid-pts** [comment]
Thanks for submitting. Adding a controller is on the roadmap for the next release.

**Comment by dxvid-pts** [comment]
I added a [roadmap](https://github.com/peterscodee/miniplayer#roadmap) for the next releases now.

**Comment by dxvid-pts** [comment]
An early implementation now landed in master. The API might change until the next version will be released. Let me know if you have feedback on this.

Implementation:
`controller.animateToHeight(state: PanelState.MAX);`

**Comment by vishal-akg** [comment]
yes recent code changes works as expected! kudos!!
