### ISSUE TITLE
MiniController animation functionally won't work after parent widget rebuilds.

### ISSUE THREAD

**Issue by vishal-akg** [peterscodee/miniplayer#6]
As listener is attached to `Minicontroller` inside initState widget life cycle method but Mini player is very likely to be recreated because of parent widget rebuilds ex. Safe Area change ( Device Navigation keys hide, show)  , MediaQuery and others so. 
Opacity test 0 <= opacity <= 1.0 fails too because after safe area height changes.

**Comment by dxvid-pts** [comment]
I couldn't recreate this issue. The controller is always working for me. 

> Opacity test 0 <= opacity <= 1.0

This can happen if you use a special `Curve` such as `Curves.easeInOutBack`.
