### ISSUE TITLE
Ability to go from expanded to min size on back button

### ISSUE THREAD

**Issue by alberduris** [peterscodee/miniplayer#8]
The usual behaviour when pressing the back button is to minimise the bottom sheet, not going to the previous screen or exiting the app (i.e., YouTube Music, Spotify or Google Maps).

Is it possible to get this? Thanks!

**Comment by dxvid-pts** [comment]
Sure! For now, you can build this by yourself by using `WillPopScope` and the controller, but I'll add this feature in the next days.

**Comment by dxvid-pts** [comment]
I just added the feature. Feedback if everything works as expected is appreciated.

**Comment by alberduris** [comment]
HI @peterscodee, I will try it later today and I will let you know. Have you updated the docs or something to point out how to get this behaviour? Or it is the default behaviour now? Thanks!

**Comment by alberduris** [comment]
Hi again @peterscodee, I don't know how to test the new version of the package if it is not yet released to pub.dev, if you guide through it I am willing to test this dev version

**Comment by dxvid-pts** [comment]
> Hi again @peterscodee, I don't know how to test the new version of the package if it is not yet released to pub.dev

Take a look at that: https://stackoverflow.com/questions/54022704/how-to-add-a-package-from-github-flutter



> Or it is the default behaviour now? 

Yes.

**Comment by alberduris** [comment]
Hi @peterscodee, thank you for your help! 

I've been able to test it and I think it is not working correctly. 

- When I click the back button while the player is maximized it doesn't minimise, and the previous screen goes back. 

This is, the behaviour is exactly the same as in version ^0.6.1

By the way, I am using the [second method](https://pub.dev/packages/miniplayer/example) to get persistence to show the Miniplayer, and I am following the sample you gave me in #7 

This means that I already have an `WillPopScope` widget as parent of the `Scaffold`

**Comment by dxvid-pts** [comment]
> Hi @peterscodee, thank you for your help!
> 
> I've been able to test it and I think it is not working correctly.
> 
> * When I click the back button while the player is maximized it doesn't minimise, and the previous screen goes back.
> 
> This is, the behaviour is exactly the same as in version ^0.6.1
> 
> By the way, I am using the [second method](https://pub.dev/packages/miniplayer/example) to get persistence to show the Miniplayer, and I am following the sample you gave me in #7
> 
> This means that I already have an `WillPopScope` widget as parent of the `Scaffold`

Ok, thank you for your help. I indeed only tested using the first method, so there could be a problem with nested navigators that needs further investigation. A quick fix, for now, would be pasting the code from my commit in your WillPopScope manually.

**Comment by alberduris** [comment]
Thank you for your answer. 

I've tried that but it doesn't seem that easy. From my `WillPopUp` widget I don't have access to the `heightNotifier` property or `_snapToPosition` method. So as I am still developing the app I think I prefer to wait until the next release when you get that working in a general way.

But please, if you need help during that time, let me know and I will assist the development to the best of my ability.

**Comment by dxvid-pts** [comment]
> I've tried that but it doesn't seem that easy. From my `WillPopUp` widget I don't have access to the `heightNotifier` property or `_snapToPosition` method. So as I am still developing the app I think I prefer to wait until the next release when you get that working in a general way.

You can get the current height through a custom [`valueNotifier`](https://pub.dev/packages/miniplayer#options:~:text=valueNotifier,-final) and animate to a position with a [`controller`](https://github.com/peterscodee/miniplayer/issues/5).

**Comment by alberduris** [comment]
I think I prefer to wait for the release :sweat_smile:

**Comment by dxvid-pts** [comment]
I have long thought about how to implement this feature and ended up introducing `MiniplayerWillPopScope` as a drop-in replacement for `WillPopScope` for the cleanest solution in a nested environment.

Just replace the two and you are good to go!
